import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from 'next/font/google';


const inter = Inter({
  weight: ['500'],
  subsets: ['latin'],
  variable: '--font-inter',
});



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black">
      
      <body
        className={` ${inter.variable} ${geistSans.variable} ${geistMono.variable} antialiased bg-[#0a0a0a] text-[#ededed] font-inter min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
